# Import discord
import discord
# Import undocumented part of Discord to use commands
from discord.ext import commands
# Import Sakanya Core
from __main__ import SakanyaCore
# Import os for file system checks
import os
# Import aiohttp for asynchronous HTTP requests
import aiohttp
# Import JSON to handle json responses
import json

class FileManagement():
  def __init__(self, bot):
    self.bot = bot

  @commands.command(pass_context=True)
  async def emptyfile(self, context, filename=None):
    """
    Empty a file
    
    Format:
      >emptyfile [filename]

    Examples:
      >emptyfile nullstory.txt
    """ 
    if context.message.author.id != '202501452596379648':
      return
    if filename is None:
      await self.bot.say('A file name has to be specified.')
      return
    try: 
      file = open(filename, 'w', encoding='utf8')
      file.write('')
      file.close()
      await self.bot.say('Emptied file ' + filename)
    except Exception as e:
      await self.bot.say('Error: ' + str(e))

  @commands.command(pass_context=True)
  async def readfile(self, context, filename=None):
    """
    Read a file
    
    Format:
      >readfile [filename]

    Examples:
      >readfile nullstory.txt
    """
    if context.message.author.id != '202501452596379648':
      return
    if filename is None:
      await self.bot.say('A file name has to be specified.')
      return
    try: 
      with open(filename, encoding='utf8') as f:
        contents = f.read()
        # contents = (contents[:1800] + '...') if len(contents) > 1802 else contents
        async with aiohttp.ClientSession() as session:
          try:
            data = {
              'description': 'Automatically generated by FoxInFlame/Sakanya',
              'public': 'false',
              'files': {}
            }
            data['files'][filename.replace('/', '-')] = {
              'content': contents
            }
            response = await session.post(url='https://api.github.com/gists', data=json.dumps(data), headers=SakanyaCore().headers, allow_redirects=False)

            async with response:
              urlresult = json.loads(await response.text())
              if 'url' not in urlresult:
                await self.bot.say(embed=discord.Embed(
                  color = SakanyaCore().embed_color,
                  title = 'File: ' + filename,
                  type = 'rich',
                  description = urlresult['message']
                ))
                return
              await self.bot.say(embed=discord.Embed(
                color = SakanyaCore().embed_color,
                title = 'File: ' + filename,
                type = 'rich',
                description = 'Uploaded to:\n[{0}]({1})'.format(urlresult['html_url'], urlresult['html_url'])
              ))
          except Exception as e:
            print(repr(e))
            print('Couldn\'t access github.com.')
            await self.bot.say(embed=discord.Embed(
              color = SakanyaCore().embed_color,
              title = 'File: ' + filename,
              type = 'rich',
              description = 'Could not access api.github.com. Maybe it\'s down?\n{}'.format(repr(e))
            ))

    except Exception as e:
      await self.bot.say('Error: ' + str(e))
def setup(bot):
  bot.add_cog(FileManagement(bot))
